DROP DATABASE IF EXISTS `platform`;
CREATE DATABASE IF NOT EXISTS `platform` ;

DROP DATABASE IF EXISTS `report`;
CREATE DATABASE  IF NOT EXISTS `report` ;

DROP DATABASE IF EXISTS `wagers`;
CREATE DATABASE  IF NOT EXISTS `wagers` ;
